export const PREGUNTAS_POR_SIMULACRO = 20
export const TIEMPO_POR_PREGUNTA_SEGUNDOS = 90

export const ESPECIALIDADES = [
  'Anatomía',
  'Anestesiología',
  'Bioquímica',
  'Cardiología',
  'Cirugía General',
  'Dermatología',
  'Endocrinología',
  'Epidemiología y Salud Pública',
  'Farmacología',
  'Fisiología',
  'Gastroenterología',
  'Genética',
  'Ginecología y Obstetricia',
  'Hematología',
  'Infectología',
  'Inmunología',
  'Medicina de Urgencias',
  'Medicina Interna',
  'Nefrología',
  'Neumología',
  'Neurocirugía',
  'Neurología',
  'Oftalmología',
  'Oncología',
  'Otorrinolaringología',
  'Patología',
  'Pediatría',
  'Psiquiatría',
  'Radiología',
  'Reumatología',
  'Traumatología y Ortopedia',
  'Urología',
] as const

const ESPECIALIDAD_MAP: Record<string, string> = {
  // Accent-less variations
  'Cardiologia': 'Cardiología',
  'Endocrinologia': 'Endocrinología',
  'Nefrologia': 'Nefrología',
  'Neumologia': 'Neumología',
  'Neurologia': 'Neurología',
  'Pediatria': 'Pediatría',
  'Cirugía general': 'Cirugía General',

  // Old names / synonyms
  'Digestivo': 'Gastroenterología',
  'Infecciosas': 'Infectología',
  'Enfermedades Infecciosas': 'Infectología',
  'ORL': 'Otorrinolaringología',
  'Anatomía Patológica': 'Patología',
  'Bioética': 'Medicina Interna',
  'Estadística': 'Epidemiología y Salud Pública',
  'Medicina Preventiva': 'Epidemiología y Salud Pública',
  'Ginecología': 'Ginecología y Obstetricia',
  'Traumatología': 'Traumatología y Ortopedia',

  // Sub-specialties → parent
  'Biología celular': 'Bioquímica',
  'Biología Celular': 'Bioquímica',
  'Biología molecular': 'Bioquímica',
  'Biología Molecular': 'Bioquímica',
  'Biología Molecular y Genética': 'Genética',
  'Bioética y Medicina Paliativa': 'Medicina Interna',
  'Cuidados paliativos': 'Oncología',
  'Cuidados Paliativos': 'Oncología',
  'Embriología': 'Anatomía',
  'Epidemiología': 'Epidemiología y Salud Pública',
  'Genética médica': 'Genética',
  'Genética Médica': 'Genética',
  'Geriatría': 'Medicina Interna',
  'Gestión en Salud': 'Epidemiología y Salud Pública',
  'Hepatología': 'Gastroenterología',
  'Medicina Crítica': 'Medicina de Urgencias',
  'Medicina de Emergencia': 'Medicina de Urgencias',
  'Medicina de Urgencias': 'Medicina de Urgencias',
  'Medicina Legal': 'Medicina Interna',
  'Medicina Paliativa': 'Oncología',
  'Microbiología': 'Infectología',
  'Neonatología': 'Pediatría',
  'Neuroanatomía': 'Neurología',
  'Neurociencias': 'Neurología',
  'Nutrición': 'Endocrinología',
  'Obstetricia': 'Ginecología y Obstetricia',
  'Ortopedia': 'Traumatología y Ortopedia',
  'Parasitología': 'Infectología',
  'Salud Pública': 'Epidemiología y Salud Pública',
  'Toxicología': 'Farmacología',
  'Urgencias': 'Medicina de Urgencias',

  // Cirugía variants
  'Cirugía': 'Cirugía General',
  'Cirugía Cardiovascular': 'Cirugía General',
  'Cirugía de Cabeza y Cuello': 'Cirugía General',
  'Cirugía de Tórax': 'Cirugía General',
  'Cirugía Pediátrica': 'Cirugía General',
  'Cirugía Torácica': 'Cirugía General',
  'Cirugía Vascular': 'Cirugía General',
  'Angiología y Cirugía Vascular': 'Cirugía General',

  // Composite names with "y" / "e" that need explicit mapping
  'Obstetricia y Ginecología': 'Ginecología y Obstetricia',
  'Ortopedia y Traumatología': 'Traumatología y Ortopedia',
  'Epidemiología y Bioestadística': 'Epidemiología y Salud Pública',
  'Epidemiología y Estadística': 'Epidemiología y Salud Pública',
  'Epidemiología y Medicina Preventiva': 'Epidemiología y Salud Pública',
  'Medicina Preventiva y Salud Pública': 'Epidemiología y Salud Pública',
  'Salud Pública y Epidemiología': 'Epidemiología y Salud Pública',
  'Endocrinología y Metabolismo': 'Endocrinología',
  'Endocrinología y Neurología': 'Endocrinología',
  'Cirugía General y del Aparato Digestivo': 'Cirugía General',
  'Cirugía General - Gastroenterología': 'Cirugía General',
  'Gastroenterología y Hepatología': 'Gastroenterología',
  'Gastroenterología y Cirugía': 'Gastroenterología',
  'Gastroenterología y Farmacología': 'Gastroenterología',
  'Gastroenterología y Oncología': 'Gastroenterología',
  'Gastroenterología y Pediatría': 'Gastroenterología',
  'Hematología y Oncología': 'Hematología',
  'Hepatología y Cirugía': 'Gastroenterología',
  'Hepatología y Oncología': 'Gastroenterología',
  'Infectología e Inmunología': 'Infectología',
  'Infectología y Farmacología': 'Infectología',
  'Infectología y Hepatología': 'Infectología',
  'Infectología y Microbiología': 'Infectología',
  'Infectología y Neurología': 'Infectología',
  'Infectología y Pediatría': 'Infectología',
  'Infectología Pediátrica': 'Infectología',
  'Inmunología y Geriatría': 'Inmunología',
  'Microbiología e Infectología': 'Infectología',
  'Neumología e Infectología': 'Neumología',
  'Neumología Pediátrica': 'Neumología',
  'Neurología y Neumología': 'Neurología',
  'Neurología y Neurocirugía': 'Neurología',
  'Neurología y Oncología': 'Neurología',
  'Neurología y Traumatología': 'Neurología',
  'Neurología Pediátrica': 'Neurología',
  'Nutrición y Medicina Preventiva': 'Endocrinología',
  'Nutrición y Metabolismo': 'Endocrinología',
  'Oftalmología y Anatomía': 'Oftalmología',
  'Oncología e Infectología': 'Oncología',
  'Oncología y Patología': 'Oncología',
  'Reumatología y Nefrología': 'Reumatología',
  'Traumatología y Cirugía Ortopédica': 'Traumatología y Ortopedia',
  'Anatomía y Neurología': 'Anatomía',
  'Bioquímica y Fisiología': 'Bioquímica',
  'Cirugía y Gastroenterología': 'Cirugía General',
  'Cirugía y Oncología': 'Cirugía General',
  'Genética y Pediatría': 'Genética',
  'Medicina de Urgencias y Emergencias': 'Medicina de Urgencias',
  'Urgencias y Emergencias': 'Medicina de Urgencias',
  'Cardiología Pediátrica': 'Cardiología',
  'Nefrología Pediátrica': 'Nefrología',
}

const CANONICAL_SET = new Set<string>(ESPECIALIDADES)

export function normalizeEspecialidad(raw: string): string {
  if (CANONICAL_SET.has(raw)) return raw
  if (ESPECIALIDAD_MAP[raw]) return ESPECIALIDAD_MAP[raw]

  const first = raw.split(/\s*\/\s*|\s+-\s+/)[0].trim()
  if (CANONICAL_SET.has(first)) return first
  if (ESPECIALIDAD_MAP[first]) return ESPECIALIDAD_MAP[first]

  return raw
}

export const ESPECIALIDAD_ICONS: Record<string, string> = {
  'Anatomía': '🦴',
  'Anestesiología': '💉',
  'Bioquímica': '🧪',
  'Cardiología': '❤️',
  'Cirugía General': '🔪',
  'Dermatología': '🧴',
  'Endocrinología': '🦋',
  'Epidemiología y Salud Pública': '📊',
  'Farmacología': '💊',
  'Fisiología': '⚙️',
  'Gastroenterología': '🫁',
  'Genética': '🧬',
  'Ginecología y Obstetricia': '🩺',
  'Hematología': '🩸',
  'Infectología': '🦠',
  'Inmunología': '🛡️',
  'Medicina de Urgencias': '🚑',
  'Medicina Interna': '🏥',
  'Nefrología': '🫘',
  'Neumología': '🌬️',
  'Neurocirugía': '🧠',
  'Neurología': '🧠',
  'Oftalmología': '👁️',
  'Oncología': '🎗️',
  'Otorrinolaringología': '👂',
  'Patología': '🔬',
  'Pediatría': '👶',
  'Psiquiatría': '🧩',
  'Radiología': '📡',
  'Reumatología': '🦵',
  'Traumatología y Ortopedia': '🦴',
  'Urología': '💧',
}

export function getScoreLabel(percentage: number): { label: string; color: string } {
  if (percentage >= 80) return { label: 'Sobresaliente', color: 'var(--success)' }
  if (percentage >= 70) return { label: 'Notable', color: 'var(--success)' }
  if (percentage >= 50) return { label: 'Aprobado', color: 'var(--accent)' }
  return { label: 'Necesitas repasar', color: 'var(--error)' }
}
